### ISSUE TITLE
SyncNestedValueMapperBase currently assumes that the value of all properties are string, which isn't the case for grid based mappers like doc type grid editor and leblender

### ISSUE THREAD

**Issue by jaandrews** [KevinJump/uSync8#467]
**Describe the bug**
I'm running an updated version of the leblender mapper from v7 in umbraco 8 and am getting an error because the json string I'm passing into the NestedContentMapper isn't encoded. Below is a trace of the error I get.

```
   System.ArgumentException: Can not convert Array to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 1234
   at uSync8.ContentEdition.Mapping.SyncNestedValueMapperBase.GetImportProperties(JObject item, IContentType docType)
   at uSync8.ContentEdition.Mapping.Mappers.NestedContentMapper.GetImportValue(String value, String editorAlias)
   at BonsaiSeed.Toolkit.Umbraco.UsyncExtensions.LeBlenderContentMapper.GetImportValue(String value, String editorAlias) in C:\Users\mugen\source\repos\ctg\BonsaiSeed.Toolkit\Umbraco\UsyncExtensions\LeBlenderContentMapper.cs:line 131
   at uSync8.ContentEdition.Mapping.Mappers.GridMapper.ProcessImport(IEnumerable`1 mappers, String editorAlias, Object value)
   at uSync8.ContentEdition.Mapping.Mappers.GridMapper.ProcessGridValues(String gridContent, Func`4 callback)
   at uSync8.ContentEdition.Mapping.SyncValueMapperCollection.GetImportValue(String value, SyncPropertyMapInfo propertyMapInfo)
   at uSync8.ContentEdition.Serializers.ContentSerializerBase`1.GetImportValue(String value, String contentTypeAlias, PropertyType propertyType, String culture, String segment)
```

when the following json data is passed into it.

```json
[
    {
        "key":"ef753356-ffc7-4a53-8590-404e3a34d621",
        "name":"Event Types - Dropdown: Select event type",
        "ncContentTypeAlias":"categoryConfig",
        "placeholder":"Industry",
        "tagSource":[
            "umb://document/58b2aa6a0f824b338d508fdf0186d320"
        ],
        "controlType":[
            "Dropdown"
        ],
        "displayInOwnLine":"0"
    },
    {
        "key":"5a76f382-a5ec-4942-ba9c-7b828d0b24b4",
        "name":"Event Locations - Dropdown: Location",
        "ncContentTypeAlias":"categoryConfig",
        "placeholder":"Location",
        "tagSource":[
            "umb://document/0716f0e85ac64eeeb616b35d92bb438f"
        ],
        "controlType":[
            "Dropdown"
        ],
        "displayInOwnLine":"0"
    }
]
```

Notice that the "tagSource" and "controlType" aren't escaped, which I'm pretty sure is why nested content is throwing the error. While the source code for my leblender mapper isn't available online, it uses the same technique that the doc type grid editor uses to ensure the content isn't double escaped, so you likely can reproduce it with that (there's a note about this in the code [here](https://github.com/KevinJump/uSync/blob/v8/8.10-main/uSync8.Community.Contrib/Mappers/DocTypeGridMapper.cs#L129)). It errors out because it assumes the value of every property is a string (see the line [here](https://github.com/KevinJump/uSync/blob/v8/8.10-main/uSync8.ContentEdition/Mapping/SyncNestedValueMapperBase.cs#L47)).

**To Reproduce**
1. Create a element doc type for nested content. You should be able to use the dropdown data type to get data that's saved as an array (alias of the data type is "Umbraco.DropDown.Flexible").
2. Created a nested content data type using that data type
3. Create another element doc type for doc type grid editor.
4. Save a page with that doc type used in the grid.
5. Make a minor change to the generated config file for that page.
6. Attempt to import that change.

**Expected behavior**
My expectation would be that the data would import without any errors.

**About your Site (please complete the following information):**
 - Umbraco Version: 8.18.5
 - uSync Version: 8.11.3
 - uSync Content Edition Version: 8.11.3
 - Browser: Chrome

**Comment by jaandrews** [comment]
I was able to fix this issue, though it feels like a hack. I modified the "GetImportProperties" method used by "NestedContentMapper" to check whether the data is a JArray or JObject and import the data slightly differently if it is. Below is the code for the modified Nested Content Mapper I'm using.

```csharp
public class FixedNestedContentMapper : NestedContentMapper, ISyncMapper {
    private readonly string docTypeAliasValue = "ncContentTypeAlias";

    public FixedNestedContentMapper(IEntityService entityService, IContentTypeService contentTypeService, IDataTypeService dataTypeService) : base(entityService, contentTypeService, dataTypeService) {
    }

    public override string GetImportValue(string value, string editorAlias) {
        var nestedJson = GetItemArray(value);
        if (nestedJson == null || !nestedJson.Any()) return value.ToString();

        foreach (var item in nestedJson.Cast<JObject>()) {
            var docType = GetDocType(item, this.docTypeAliasValue);
            if (docType == null) continue;

            GetImportPropertiesFixed(item, docType);
        }

        return JsonConvert.SerializeObject(nestedJson, Formatting.Indented);
    }

    protected JObject GetImportPropertiesFixed(JObject item, IContentType docType) {
        foreach (var property in docType.CompositionPropertyTypes) {
            if (item.ContainsKey(property.Alias)) {
                var value = item[property.Alias];
                if (value != null) {
                    if (value is JArray || value is JObject) { //new handling for non strings
                        var mappedVal = SyncValueMapperFactory.GetImportValue(JsonConvert.SerializeObject(value), property.PropertyEditorAlias);
                        item[property.Alias] = mappedVal?.ToString().GetJsonTokenValue().ExpandAllJsonInToken();
                    }
                    else {
                        var mappedVal = SyncValueMapperFactory.GetImportValue((string)value, property.PropertyEditorAlias);
                        item[property.Alias] = mappedVal?.ToString();
                    }
                }
            }
        }

        return item;

    }

    private JArray GetItemArray(object value) {
        var stringValue = GetValueAs<string>(value);
        if (string.IsNullOrWhiteSpace(stringValue) || !stringValue.DetectIsJson())
            return null;

        var token = JToken.Parse(stringValue);
        switch (token) {
            case JArray array: return array;
            case JObject obj: return new JArray(obj);
            default: return null;
        }
    }
}
```
Should be possible to apply this change in the SyncNestedValueMapperBase class to fix this issue for all mappers that use it, though there might be a better solution.

**Comment by KevinJump** [comment]
Hi yes - in theory this should be better 👍 

 I will set aside some time to check, we have been burnt in the past some of the more 'complex' properties require it in one format or another but will half work when it's in the wrong format (e.g. they work in the back office but then don't render on a page or the other way around).

So i suspect this will work, but I will have to fully load a site with all the property editors and make sure we don't break anything down the line.

**Comment by jaandrews** [comment]
Yeah. This shouldn't break anything that isn't already broken, but it's possible that it will still error out on deeper mappers once it's past this error.

**Comment by jaandrews** [comment]
Just ran into another case of this problem, but this time with a data type that comes with umbraco out of the box. When I use the "Repeatable textstrings" data type in a nested content data type, the data ends up double serialized, resulting in a bunch of empty textstrings in the control when it renders in the backoffice, since it's treating that string as an array.

**Comment by jaandrews** [comment]
One possible solution would be to update the GetImportValue to return an object instead of a string so that the unescaped data could be returned to the nested content GetImportValue call (similar to what's done in umbraco's value converters). Some logic would then need to be added to ensure the data is serialized when it's saved to the config file. This would be a breaking change, but should resolve this issue.

**Comment by KevinJump** [comment]
Yeah - repeatable strings has a history - it once was storing itself in a way that included blanks. 

I agree longer term we do need to shift that method to objects and rationalize the serialization, but that is a full on breaking change and it isn't going to happen before a v13 release. 

I am going to look tomorrow at what we can do to rationalize this down in "legacy" versions 😉  - mainly because we do have quite a bit of JSON cleaning stuff in the code at the moment and it should be able to iron out some of the irregularities. 

but due to the nature of the changes in v13 (including deprecating Newtonstoft) - i don't think its something we will wholesale change just now.

**Comment by KevinJump** [comment]
> Just ran into another case of this problem, but this time with a data type that comes with umbraco out of the box. When I use the "Repeatable textstrings" data type in a nested content data type, the data ends up double serialized, resulting in a bunch of empty textstrings in the control when it renders in the backoffice, since it's treating that string as an array.

OK, So trying this  _(Umb 8.8.15 uSync 8.11.3 - but also on source at Umb 8.6.0)_

I can't get it to double escape, but repeatable text strings are odd. (i remember them, now!).

When they are in their own element - they are stored as strings with a new line. 

e.g 

```
    "repeatableText": "One\r\nTwo\r\nThree",
```

when the are in the grid - they are stored as JSON 

```
"repeatable": [
    {
      "value": "One"
    },
    {
      "value": "Two"
    },
    {
      "value": "Three"
    },
    {
      "value": "Four"
    }
  ]
```

It's odd - but it's actually what Umbraco is doing, because we don't actually map the repeatable values _(we do replace \n with \r\n because that is a legacy issue with the repeatable property back in v7 days- but we don't do anything else)_

**So**
When they are in nested content they are stored as string on a new line, **Unless** the nested content is in the grid and then they are stored as JSON.

But at the moment both of those things are working for me..

The investigation continues.

**Comment by KevinJump** [comment]
Putting the fix above in doesn't seem to break the other properties 🤞 - it did do something to the doctype Grid editor but that appears to be because we didn't check a null on the returning mapped property - so empty nested content items inside DTGE broke (this might have been true anyway). 

I think the grid's need to escape things still happens (because it unescapes any escaped sub properties as needed). 

Still going to do a *lot* of test - because i am really wary of changing this on the v8 codebase which hasn't really been updated in any significant way for 12 months+ now.

**Comment by jaandrews** [comment]
Forgot to mention it, but I did encounter the repeatable string issue when testing in umbraco 10.4.0 with usync 10.3.2, so it affects more recent versions of usync too. Same fix should work, as the way the data is stored the same way, but something to check when testing.

**Comment by KevinJump** [comment]
Ahh ok i will check, because the repeatable string thing worked for me in v8 before I did any fixing.

**Comment by KevinJump** [comment]
the fixes above have been in since v11.1 and v10.5 so hopefully they are working now for everyone.
